package com.gxl.entity;

// Generated 2016-10-25 21:07:06 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PFunction generated by hbm2java
 */
@Entity
@Table(name = "p_function", catalog = "mydb")
public class PFunction implements java.io.Serializable {

	private String funcId;
	private String funcCode;
	private String funcName;
	private String funcIcon;
	private String funcSort;
	private String funcState;
	private String funcDesc;
	private String createrId;
	private String createTime;
	private String updaterId;
	private String updateTime;

	public PFunction() {
	}

	public PFunction(String funcId, String funcCode, String funcName,
			String funcSort, String funcState, String createrId,
			String createTime) {
		this.funcId = funcId;
		this.funcCode = funcCode;
		this.funcName = funcName;
		this.funcSort = funcSort;
		this.funcState = funcState;
		this.createrId = createrId;
		this.createTime = createTime;
	}

	public PFunction(String funcId, String funcCode, String funcName,
			String funcIcon, String funcSort, String funcState,
			String funcDesc, String createrId, String createTime,
			String updaterId, String updateTime) {
		this.funcId = funcId;
		this.funcCode = funcCode;
		this.funcName = funcName;
		this.funcIcon = funcIcon;
		this.funcSort = funcSort;
		this.funcState = funcState;
		this.funcDesc = funcDesc;
		this.createrId = createrId;
		this.createTime = createTime;
		this.updaterId = updaterId;
		this.updateTime = updateTime;
	}

	@Id
	@Column(name = "func_id", unique = true, nullable = false, length = 32)
	public String getFuncId() {
		return this.funcId;
	}

	public void setFuncId(String funcId) {
		this.funcId = funcId;
	}

	@Column(name = "func_code", nullable = false, length = 20)
	public String getFuncCode() {
		return this.funcCode;
	}

	public void setFuncCode(String funcCode) {
		this.funcCode = funcCode;
	}

	@Column(name = "func_name", nullable = false, length = 20)
	public String getFuncName() {
		return this.funcName;
	}

	public void setFuncName(String funcName) {
		this.funcName = funcName;
	}

	@Column(name = "func_icon", length = 32)
	public String getFuncIcon() {
		return this.funcIcon;
	}

	public void setFuncIcon(String funcIcon) {
		this.funcIcon = funcIcon;
	}

	@Column(name = "func_sort", nullable = false, length = 2)
	public String getFuncSort() {
		return this.funcSort;
	}

	public void setFuncSort(String funcSort) {
		this.funcSort = funcSort;
	}

	@Column(name = "func_state", nullable = false, length = 2)
	public String getFuncState() {
		return this.funcState;
	}

	public void setFuncState(String funcState) {
		this.funcState = funcState;
	}

	@Column(name = "func_desc", length = 512)
	public String getFuncDesc() {
		return this.funcDesc;
	}

	public void setFuncDesc(String funcDesc) {
		this.funcDesc = funcDesc;
	}

	@Column(name = "creater_id", nullable = false, length = 32)
	public String getCreaterId() {
		return this.createrId;
	}

	public void setCreaterId(String createrId) {
		this.createrId = createrId;
	}

	@Column(name = "create_time", nullable = false, length = 14)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "updater_id", length = 32)
	public String getUpdaterId() {
		return this.updaterId;
	}

	public void setUpdaterId(String updaterId) {
		this.updaterId = updaterId;
	}

	@Column(name = "update_time", length = 14)
	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

}
