package com.gxl.entity;

// Generated 2016-12-29 23:01:16 by Hibernate Tools 3.4.0.CR1

/**
 * PMbrInfo generated by hbm2java
 */
public class PMbrInfo implements java.io.Serializable {

	private String mbrId;
	private String mbrName;
	private String sex;
	private String age;
	private String constellation;
	private String height;
	private String bloodType;
	private String weight;
	private String occupation;
	private String education;
	private String marryStatus;
	private String monthIncome;
	private String nativePlace;
	private String havaHouse;
	private String birthday;
	private String location;
	private String picUrl;
	private String type;
	private String origin;

	public PMbrInfo() {
	}

	public PMbrInfo(String mbrId, String mbrName, String sex,
			String constellation, String bloodType, String weight,
			String occupation, String marryStatus, String monthIncome,
			String havaHouse, String birthday, String type, String origin) {
		this.mbrId = mbrId;
		this.mbrName = mbrName;
		this.sex = sex;
		this.constellation = constellation;
		this.bloodType = bloodType;
		this.weight = weight;
		this.occupation = occupation;
		this.marryStatus = marryStatus;
		this.monthIncome = monthIncome;
		this.havaHouse = havaHouse;
		this.birthday = birthday;
		this.type = type;
		this.origin = origin;
	}

	public PMbrInfo(String mbrId, String mbrName, String sex, String age,
			String constellation, String height, String bloodType,
			String weight, String occupation, String education,
			String marryStatus, String monthIncome, String nativePlace,
			String havaHouse, String birthday, String location, String picUrl,
			String type, String origin) {
		this.mbrId = mbrId;
		this.mbrName = mbrName;
		this.sex = sex;
		this.age = age;
		this.constellation = constellation;
		this.height = height;
		this.bloodType = bloodType;
		this.weight = weight;
		this.occupation = occupation;
		this.education = education;
		this.marryStatus = marryStatus;
		this.monthIncome = monthIncome;
		this.nativePlace = nativePlace;
		this.havaHouse = havaHouse;
		this.birthday = birthday;
		this.location = location;
		this.picUrl = picUrl;
		this.type = type;
		this.origin = origin;
	}

	public String getMbrId() {
		return this.mbrId;
	}

	public void setMbrId(String mbrId) {
		this.mbrId = mbrId;
	}

	public String getMbrName() {
		return this.mbrName;
	}

	public void setMbrName(String mbrName) {
		this.mbrName = mbrName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getConstellation() {
		return this.constellation;
	}

	public void setConstellation(String constellation) {
		this.constellation = constellation;
	}

	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getBloodType() {
		return this.bloodType;
	}

	public void setBloodType(String bloodType) {
		this.bloodType = bloodType;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getMarryStatus() {
		return this.marryStatus;
	}

	public void setMarryStatus(String marryStatus) {
		this.marryStatus = marryStatus;
	}

	public String getMonthIncome() {
		return this.monthIncome;
	}

	public void setMonthIncome(String monthIncome) {
		this.monthIncome = monthIncome;
	}

	public String getNativePlace() {
		return this.nativePlace;
	}

	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace;
	}

	public String getHavaHouse() {
		return this.havaHouse;
	}

	public void setHavaHouse(String havaHouse) {
		this.havaHouse = havaHouse;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

}
