package com.gxl.entity;

// Generated 2016-12-29 23:01:16 by Hibernate Tools 3.4.0.CR1

/**
 * PMember generated by hbm2java
 */
public class PMember implements java.io.Serializable {

	private String mbrId;
	private String password;
	private String phone;
	private String email;
	private String qqNo;
	private String weixinNo;
	private String registerTime;
	private String recommenderId;

	public PMember() {
	}

	public PMember(String mbrId, String password, String registerTime,
			String recommenderId) {
		this.mbrId = mbrId;
		this.password = password;
		this.registerTime = registerTime;
		this.recommenderId = recommenderId;
	}

	public PMember(String mbrId, String password, String phone, String email,
			String qqNo, String weixinNo, String registerTime,
			String recommenderId) {
		this.mbrId = mbrId;
		this.password = password;
		this.phone = phone;
		this.email = email;
		this.qqNo = qqNo;
		this.weixinNo = weixinNo;
		this.registerTime = registerTime;
		this.recommenderId = recommenderId;
	}

	public String getMbrId() {
		return this.mbrId;
	}

	public void setMbrId(String mbrId) {
		this.mbrId = mbrId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getQqNo() {
		return this.qqNo;
	}

	public void setQqNo(String qqNo) {
		this.qqNo = qqNo;
	}

	public String getWeixinNo() {
		return this.weixinNo;
	}

	public void setWeixinNo(String weixinNo) {
		this.weixinNo = weixinNo;
	}

	public String getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(String registerTime) {
		this.registerTime = registerTime;
	}

	public String getRecommenderId() {
		return this.recommenderId;
	}

	public void setRecommenderId(String recommenderId) {
		this.recommenderId = recommenderId;
	}

}
