package com.gxl.entity;

// Generated 2017-1-9 21:50:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PMember generated by hbm2java
 */
@Entity
@Table(name = "p_member", catalog = "mydb")
public class PMember implements java.io.Serializable {

	private String mbrId;
	private String password;
	private String phone;
	private String email;
	private String qqNo;
	private String weixinNo;
	private String registerTime;
	private String recommenderId;

	public PMember() {
	}

	public PMember(String mbrId, String password, String registerTime,
			String recommenderId) {
		this.mbrId = mbrId;
		this.password = password;
		this.registerTime = registerTime;
		this.recommenderId = recommenderId;
	}

	public PMember(String mbrId, String password, String phone, String email,
			String qqNo, String weixinNo, String registerTime,
			String recommenderId) {
		this.mbrId = mbrId;
		this.password = password;
		this.phone = phone;
		this.email = email;
		this.qqNo = qqNo;
		this.weixinNo = weixinNo;
		this.registerTime = registerTime;
		this.recommenderId = recommenderId;
	}

	@Id
	@Column(name = "mbr_id", unique = true, nullable = false, length = 32)
	public String getMbrId() {
		return this.mbrId;
	}

	public void setMbrId(String mbrId) {
		this.mbrId = mbrId;
	}

	@Column(name = "password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "phone", length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", length = 32)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "qq_no", length = 12)
	public String getQqNo() {
		return this.qqNo;
	}

	public void setQqNo(String qqNo) {
		this.qqNo = qqNo;
	}

	@Column(name = "weixin_no", length = 16)
	public String getWeixinNo() {
		return this.weixinNo;
	}

	public void setWeixinNo(String weixinNo) {
		this.weixinNo = weixinNo;
	}

	@Column(name = "register_time", nullable = false, length = 14)
	public String getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(String registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "recommender_id", nullable = false, length = 32)
	public String getRecommenderId() {
		return this.recommenderId;
	}

	public void setRecommenderId(String recommenderId) {
		this.recommenderId = recommenderId;
	}

}
