package com.gxl.entity;

// Generated 2016-10-18 12:09:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PMenu generated by hbm2java
 */
@Entity
@Table(name = "p_menu", catalog = "mydb")
public class PMenu implements java.io.Serializable {

	private String menuId;
	private String menuName;
	private String menuType;
	private String menuProp;
	private String menuSort;
	private String menuState;
	private String upMenuId;
	private String menuIcon;
	private String menuLink;
	private String menuDesc;
	private String createrId;
	private String createTime;
	private String updaterId;
	private String updateTime;

	public PMenu() {
	}

	public PMenu(String menuId, String menuName, String menuType,
			String menuProp, String menuSort, String menuState,
			String createrId, String createTime) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.menuType = menuType;
		this.menuProp = menuProp;
		this.menuSort = menuSort;
		this.menuState = menuState;
		this.createrId = createrId;
		this.createTime = createTime;
	}

	public PMenu(String menuId, String menuName, String menuType,
			String menuProp, String menuSort, String menuState,
			String upMenuId, String menuIcon, String menuLink, String menuDesc,
			String createrId, String createTime, String updaterId,
			String updateTime) {
		this.menuId = menuId;
		this.menuName = menuName;
		this.menuType = menuType;
		this.menuProp = menuProp;
		this.menuSort = menuSort;
		this.menuState = menuState;
		this.upMenuId = upMenuId;
		this.menuIcon = menuIcon;
		this.menuLink = menuLink;
		this.menuDesc = menuDesc;
		this.createrId = createrId;
		this.createTime = createTime;
		this.updaterId = updaterId;
		this.updateTime = updateTime;
	}

	@Id
	@Column(name = "menu_id", unique = true, nullable = false, length = 32)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	@Column(name = "menu_name", nullable = false, length = 32)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "menu_type", nullable = false, length = 2)
	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	@Column(name = "menu_prop", nullable = false, length = 2)
	public String getMenuProp() {
		return this.menuProp;
	}

	public void setMenuProp(String menuProp) {
		this.menuProp = menuProp;
	}

	@Column(name = "menu_sort", nullable = false, length = 2)
	public String getMenuSort() {
		return this.menuSort;
	}

	public void setMenuSort(String menuSort) {
		this.menuSort = menuSort;
	}

	@Column(name = "menu_state", nullable = false, length = 2)
	public String getMenuState() {
		return this.menuState;
	}

	public void setMenuState(String menuState) {
		this.menuState = menuState;
	}

	@Column(name = "up_menu_id", length = 32)
	public String getUpMenuId() {
		return this.upMenuId;
	}

	public void setUpMenuId(String upMenuId) {
		this.upMenuId = upMenuId;
	}

	@Column(name = "menu_icon", length = 32)
	public String getMenuIcon() {
		return this.menuIcon;
	}

	public void setMenuIcon(String menuIcon) {
		this.menuIcon = menuIcon;
	}

	@Column(name = "menu_link", length = 64)
	public String getMenuLink() {
		return this.menuLink;
	}

	public void setMenuLink(String menuLink) {
		this.menuLink = menuLink;
	}

	@Column(name = "menu_desc", length = 512)
	public String getMenuDesc() {
		return this.menuDesc;
	}

	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc;
	}

	@Column(name = "creater_id", nullable = false, length = 32)
	public String getCreaterId() {
		return this.createrId;
	}

	public void setCreaterId(String createrId) {
		this.createrId = createrId;
	}

	@Column(name = "create_time", nullable = false, length = 14)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "updater_id", length = 32)
	public String getUpdaterId() {
		return this.updaterId;
	}

	public void setUpdaterId(String updaterId) {
		this.updaterId = updaterId;
	}

	@Column(name = "update_time", length = 14)
	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

}
