package com.gxl.entity;

// Generated 2016-10-23 15:27:16 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PRole generated by hbm2java
 */
@Entity
@Table(name = "p_role", catalog = "mydb")
public class PRole implements java.io.Serializable {

	private String roleId;
	private String roleName;
	private String roleDesc;
	private String roleState;
	private String createrId;
	private String createTime;
	private String updaterId;
	private String updateTime;

	public PRole() {
	}

	public PRole(String roleId, String roleName, String roleState,
			String createrId, String createTime) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleState = roleState;
		this.createrId = createrId;
		this.createTime = createTime;
	}

	public PRole(String roleId, String roleName, String roleDesc,
			String roleState, String createrId, String createTime,
			String updaterId, String updateTime) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.roleState = roleState;
		this.createrId = createrId;
		this.createTime = createTime;
		this.updaterId = updaterId;
		this.updateTime = updateTime;
	}

	@Id
	@Column(name = "role_id", unique = true, nullable = false, length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", nullable = false, length = 32)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_desc", length = 512)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@Column(name = "role_state", nullable = false, length = 2)
	public String getRoleState() {
		return this.roleState;
	}

	public void setRoleState(String roleState) {
		this.roleState = roleState;
	}

	@Column(name = "creater_id", nullable = false, length = 32)
	public String getCreaterId() {
		return this.createrId;
	}

	public void setCreaterId(String createrId) {
		this.createrId = createrId;
	}

	@Column(name = "create_time", nullable = false, length = 14)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "updater_id", length = 32)
	public String getUpdaterId() {
		return this.updaterId;
	}

	public void setUpdaterId(String updaterId) {
		this.updaterId = updaterId;
	}

	@Column(name = "update_time", length = 14)
	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

}
