package com.gxl.entity;

// Generated 2016-10-18 12:09:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PUser generated by hbm2java
 */
@Entity
@Table(name = "p_user", catalog = "mydb")
public class PUser implements java.io.Serializable {

	private String userId;
	private String userNo;
	private String userPwd;
	private String userName;
	private String roleId;
	private String deptId;
	private String userLevel;
	private String userPhone;
	private String userEmail;
	private String userState;
	private String isOnline;
	private String onlineIp;
	private String createrId;
	private String createTime;
	private String updaterId;
	private String updateTime;

	public PUser() {
	}

	public PUser(String userId, String userNo, String userPwd,
			String userState, String isOnline, String createrId,
			String createTime) {
		this.userId = userId;
		this.userNo = userNo;
		this.userPwd = userPwd;
		this.userState = userState;
		this.isOnline = isOnline;
		this.createrId = createrId;
		this.createTime = createTime;
	}

	public PUser(String userId, String userNo, String userPwd, String userName,
			String roleId, String deptId, String userLevel, String userPhone,
			String userEmail, String userState, String isOnline,
			String onlineIp, String createrId, String createTime,
			String updaterId, String updateTime) {
		this.userId = userId;
		this.userNo = userNo;
		this.userPwd = userPwd;
		this.userName = userName;
		this.roleId = roleId;
		this.deptId = deptId;
		this.userLevel = userLevel;
		this.userPhone = userPhone;
		this.userEmail = userEmail;
		this.userState = userState;
		this.isOnline = isOnline;
		this.onlineIp = onlineIp;
		this.createrId = createrId;
		this.createTime = createTime;
		this.updaterId = updaterId;
		this.updateTime = updateTime;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_no", nullable = false, length = 20)
	public String getUserNo() {
		return this.userNo;
	}

	public void setUserNo(String userNo) {
		this.userNo = userNo;
	}

	@Column(name = "user_pwd", nullable = false, length = 32)
	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	@Column(name = "user_name", length = 32)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "dept_id", length = 32)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@Column(name = "user_level", length = 2)
	public String getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(String userLevel) {
		this.userLevel = userLevel;
	}

	@Column(name = "user_phone", length = 20)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_email", length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_state", nullable = false, length = 2)
	public String getUserState() {
		return this.userState;
	}

	public void setUserState(String userState) {
		this.userState = userState;
	}

	@Column(name = "is_online", nullable = false, length = 2)
	public String getIsOnline() {
		return this.isOnline;
	}

	public void setIsOnline(String isOnline) {
		this.isOnline = isOnline;
	}

	@Column(name = "online_ip", length = 20)
	public String getOnlineIp() {
		return this.onlineIp;
	}

	public void setOnlineIp(String onlineIp) {
		this.onlineIp = onlineIp;
	}

	@Column(name = "creater_id", nullable = false, length = 32)
	public String getCreaterId() {
		return this.createrId;
	}

	public void setCreaterId(String createrId) {
		this.createrId = createrId;
	}

	@Column(name = "create_time", nullable = false, length = 14)
	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	@Column(name = "updater_id", length = 32)
	public String getUpdaterId() {
		return this.updaterId;
	}

	public void setUpdaterId(String updaterId) {
		this.updaterId = updaterId;
	}

	@Column(name = "update_time", length = 14)
	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

}
